## Visualization 3D Structures


#### Installing dependencies 

In [1]:
import numpy as np
from numpy import sin,cos,pi
import k3d
from ParticleGrid import coord_to_grid

In [13]:
mol_coord = \
np.array([[2.5800, -0.0846, 0.2795], 
[1.0798,0.0425,0.0073], 
[0.3586,-1.1959,0.5442], 
[-1.1382,-1.0748,0.2367], 
[-1.6446,0.2643,0.7847], 
[-0.7719,1.3922,0.2296], 
[0.5782,1.2114,0.6527],
[-0.8283,1.3778,-1.1982],
[-3.0002,0.4649,0.3793],
[-1.3428,-1.1226,-1.1768],
[0.8832,-2.3658,-0.0869],
[3.2681,1.0135,-0.3228],
[2.7560,-0.0777,1.3552],
[2.9479,-1.0196,-0.1429],
[0.9118,0.1225,-1.0667],
[0.5051,-1.2646,1.6221], 
[-1.6772,-1.8929,0.7146], 
[-1.5850,0.2589,1.8730], 
[-1.1413,2.3500,0.5962], 
[-0.2667,2.1017,-1.5074],
[-3.2780,1.3161,0.7444], 
[-2.2952,-1.0433,-1.3242], 
[0.4023,-3.1205,0.2794], 
[4.2078,0.8952,-0.1280]]) 

### Translate and Pad the Points

In [14]:
padding = 2
translation_vector = mol_coord.min(axis=0)
mol_coord = mol_coord - translation_vector
print("Translate molecule coordiantes to positive quadrant: ",mol_coord.min(axis=0))
mol_coord = mol_coord + padding
print("Pad molecule coordiantes away from quadrant boundary: ",mol_coord.min(axis=0))

Translate molecule coordiantes to positive quadrant:  [0. 0. 0.]
Pad molecule coordiantes away from quadrant boundary:  [2. 2. 2.]


In [15]:
mol_coord = np.hstack([np.zeros((24,1)),mol_coord])
print(mol_coord)

[[0.     7.858  5.0359 3.7869]
 [0.     6.3578 5.163  3.5147]
 [0.     5.6366 3.9246 4.0516]
 [0.     4.1398 4.0457 3.7441]
 [0.     3.6334 5.3848 4.2921]
 [0.     4.5061 6.5127 3.737 ]
 [0.     5.8562 6.3319 4.1601]
 [0.     4.4497 6.4983 2.3092]
 [0.     2.2778 5.5854 3.8867]
 [0.     3.9352 3.9979 2.3306]
 [0.     6.1612 2.7547 3.4205]
 [0.     8.5461 6.134  3.1846]
 [0.     8.034  5.0428 4.8626]
 [0.     8.2259 4.1009 3.3645]
 [0.     6.1898 5.243  2.4407]
 [0.     5.7831 3.8559 5.1295]
 [0.     3.6008 3.2276 4.222 ]
 [0.     3.693  5.3794 5.3804]
 [0.     4.1367 7.4705 4.1036]
 [0.     5.0113 7.2222 2.    ]
 [0.     2.     6.4366 4.2518]
 [0.     2.9828 4.0772 2.1832]
 [0.     5.6803 2.     3.7868]
 [0.     9.4858 6.0157 3.3794]]


### Generate Grid

In [39]:
bounding_cube_size = mol_coord.max() + padding 
print("Bounding cube side dimension: ", bounding_cube_size)
grid = coord_to_grid(mol_coord,
                     width=bounding_cube_size,
                     height=bounding_cube_size,
                     depth=bounding_cube_size,
                     num_channels=1,
                     grid_size=32,
                     variance=0.25)

Bounding cube side dimension:  11.4858


In [43]:
grid.max()

0.13938503

In [48]:
plot = k3d.plot()

volume = k3d.volume(grid.sum(0).astype(np.float32),
                    alpha_coef=100,
                    shadow='off', #dynamic is a fancy option but require a good GPU
                    color_range = [grid.min(), grid.max()],
                    color_map = k3d.colormaps.matplotlib_color_maps.Jet,
                    samples=1200)
plot += volume
plot.display()

Output()