In [1]:
from Periodic import CrystalParams
import numpy as np
import k3d

### Create a CrystalParams

The necessary information required to generated a crystal is encapsulated in the `CrystalParams` class. The required inputs to create a class is as follows:

- A : (float) lattice constant length a  
- B : (float) lattice constant length b
- C : (float) lattice constant length c
- alpha : (float) lattice constant angle alpha (in radians)
- beta : (float) lattice constant angle beta (in radians)
- gamma : (float) lattice constant angle gamma (in radians)
- coords : (NDarray: N, 4) Fractional coordinates of atoms with associated channels concatenated at the end
- element : (NDarray: N,) Atomic number of of each atom in order

When constructing the objet, ParticleGrid will internally calculate the appropriate transformation matrix and expaned the atom list to account of boundary atoms

In [2]:
coords = np.array(
        [
            [0, 0, 0, 0],
            [0, 0.5, 0.5, 0],
            [0.5, 0, 0.5, 0],
            [0.5, 0.5, 0, 0],
            [0.5, 0.5, 0.5, 1],
        ]
    )
elements = np.array([0, 0, 0, 0, 1])
params = CrystalParams(
    A=10,
    B=10,
    C=10,
    alpha=np.pi / 2,
    beta=np.pi / 2,
    gamma=np.pi / 2,
    coords=coords,
    elements=elements,
)

In [3]:
# To String Method
print(params)

Lattice parameters: 
A:	10.000000
B:	10.000000
C:	10.000000 
Alpha:	1.570796
Beta:	1.570796
Gamma:	1.570796



In [4]:
# Print the expanded coordinates
print(params.get_cartesian_coords())

[[ 0.  0.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0. 10.  0.  0.]
 [ 0. 10. 10.  0.]
 [10.  0.  0.  0.]
 [10.  0. 10.  0.]
 [10. 10.  0.  0.]
 [10. 10. 10.  0.]
 [ 0.  5.  5.  0.]
 [10.  5.  5.  0.]
 [ 5.  0.  5.  0.]
 [ 5. 10.  5.  0.]
 [ 5.  5.  0.  0.]
 [ 5.  5. 10.  0.]
 [ 5.  5.  5.  1.]]


In [5]:
# Print the atom elements
print(params.get_elements())

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [6]:
print(params.get_transform_matrix())

[[10.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 10.]]


In [7]:
energy_grid = params.LJ_Grid(32)

In [36]:
capped_grid = np.copy(energy_grid)
min_val = -5000
max_val = 5000
capped_grid[capped_grid > max_val] = max_val
capped_grid[capped_grid < min_val] = min_val 
capped_grid = (2 / (max_val-min_val))*(capped_grid - min_val) - 1

In [37]:
capped_grid.min(), capped_grid.max()

(-0.01671946, 0.032500505)

In [38]:
plot = k3d.plot()

# for level in [-1, -2, -3, -6]: 
plt_marching = k3d.marching_cubes(capped_grid[0], level=-0.9,
                                  color=0x0e2763,
                                  opacity=0.2,
                                  xmin=0, xmax=32,
                                  ymin=0, ymax=32,
                                  zmin=0, zmax=32,
                                  compression_level=9,
                                  flat_shading=False,
                                  translation=[4,4,4])
    
    
plot += plt_marching

plot.display()

Output()

In [17]:
prob_grid = params.Probability_Grid(32, 1)

In [19]:
plot = k3d.plot()

# updates level to change size of isosurface
plt_marching = k3d.marching_cubes(prob_grid[0], level=0.0002,
                                  color=0x0e2763,
                                  opacity=0.2,
                                  xmin=0, xmax=32,
                                  ymin=0, ymax=32,
                                  zmin=0, zmax=32,
                                  compression_level=9,
                                  flat_shading=False,
                                  translation=[4,4,4])
plot += plt_marching

plt_marching = k3d.marching_cubes(prob_grid[1], level=0.0001,
                                  color=0x620e30,
                                  opacity=0.2,
                                  xmin=0, xmax=32,
                                  ymin=0, ymax=32,
                                  zmin=0, zmax=32,
                                  compression_level=9,
                                  flat_shading=False,
                                  translation=[4,4,4])
plot += plt_marching

plt_marching = k3d.marching_cubes(capped_grid[0], level=-0.9,
                                  color=0x0e2763,
                                  opacity=0.2,
                                  xmin=0, xmax=32,
                                  ymin=0, ymax=32,
                                  zmin=0, zmax=32,
                                  compression_level=9,
                                  flat_shading=False,
                                  translation=[4,4,4])
plot.display()

Output()